version: "3.6"

services:
  db:
    image: mysql/mysql-server:latest
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "MYSQL_USER=${DB_USER}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_DATABASE=${DB_NAME}"

  web:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ".:/app"
    depends_on:
      - db
    links:
      - "db:database"
